### ISSUE TITLE
Some Problems I need to fix 

### ISSUE THREAD

**Issue by aayanrahman** [aayanrahman/WOSS-Economics-Club-Website#1]
Spelt olympiad wrong under yuehangs photo its not olympaid 
Make it better mobile optimised as on iphones the registration h1 tag falls outside of the page 
Make a production pipeline with netlify to be able to commit changes and have version control

**Comment by Solidisitch** [comment]
Change Halton Economics Olympiad to WOSS Economics Olympiad

**Comment by Solidisitch** [comment]
Shows privacy error when you click on the link
